mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.final_project.community_zone.entity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_final?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver